### ISSUE TITLE
LINQ queries for MemberGridView and InstructorGridView do not properly display elements

### ISSUE THREAD

**Issue by cjstepan** [cjstepan/KarateSchool#1]
On page load, GridViews for Members and Instructors should automatically show up. The GridViews should not be directly connected to the database tables, since we don't want all of that information to be displayed. Rather, we want a filtered display based on the requirements in the assignment doc. The queries should already be written, but something is preventing them from displaying information on page load.

**Comment by rgablr** [comment]
I had to just delete the current grid views and start from scratch, everything looked right, even when I made the new grid views the LINQ queries were basically 1:1. not sure if it was the way the grid views were styled in HTML or what.
